<a href="https://colab.research.google.com/github/nishachaudhary6396/MachineLearning/blob/LinearAlgebraStatistics/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("hdfc_loan.csv")

In [ ]:
df

,Loan_ID,Bank,Customer_Name,Gender,Married,Dependents,Education,Employment_Status,Applicant_Income,Coapplicant_Income,...,Loan_to_Annual_Income,Customer_Sentiment,Religion,State,City,PIN_Code,Aadhaar_Synthetic,Phone_Number,Email,Occupation
0,HDFC100001,HDFC Bank,Rohan Verma,Male,No,2,Graduate,Salaried,56976,0,...,11.747,Positive,Hindu,Delhi,Dwarka,857743,6.940000e+11,9068671773,rohan.verma@example.in,Farmer
1,HDFC100002,HDFC Bank,Rohan Verma,Male,No,0,Graduate,Unemployed,1856,0,...,40.381,Negative,Hindu,Punjab,Ludhiana,863836,6.330000e+11,9990772625,rohan.verma@example.in,Civil Engineer
2,HDFC100003,HDFC Bank,Aditya Nair,Female,Yes,0,Graduate,Salaried,64553,0,...,3.082,Positive,Hindu,Maharashtra,Nagpur,834796,1.660000e+11,9195085016,aditya.nair@example.in,Medical Representative
3,HDFC100004,HDFC Bank,Ananya Joshi,Male,No,0,Graduate,Salaried,88450,0,...,0.621,Negative,Hindu,Gujarat,Vadodara,438590,5.528183e+10,9179335548,ananya.joshi@example.in,Marketing Executive
4,HDFC100005,HDFC Bank,Harpreet Singh,Male,Yes,3,Graduate,Self-Employed,9539,0,...,1.736,Neutral,Sikh,West Bengal,Kolkata,495224,1.560000e+11,9795137116,harpreet.singh@example.in,Shopkeeper
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,HDFC100996,HDFC Bank,Simran Kaur,Male,Yes,1,Graduate,Salaried,44713,0,...,10.965,Neutral,Sikh,Tamil Nadu,Coimbatore,6635,3.830000e+11,9350952889,simran.kaur@example.in,Medical Representative
996,HDFC100997,HDFC Bank,Krishna Mehta,Male,No,2,Graduate,Salaried,70886,0,...,3.268,Negative,Hindu,Kerala,Trivandrum,217843,7.040000e+11,9176504718,krishna.mehta@example.in,Customer Support Executive
997,HDFC100998,HDFC Bank,Rohan Verma,Female,No,1,Graduate,Salaried,24392,11337,...,0.703,Positive,Hindu,Delhi,New Delhi,89211,9.954289e+10,9966866798,rohan.verma@example.in,Driver
998,HDFC100999,HDFC Bank,Ananya Joshi,Female,No,2,Graduate,Salaried,64803,94136,...,0.377,Negative,Hindu,Gujarat,Ahmedabad,532976,6.170000e+11,9103847156,ananya.joshi@example.in,Electrician


In [ ]:
data = df[['Dependents','Applicant_Income','Loan_to_Annual_Income','Coapplicant_Income','Loan_Amount','Loan_Term_Months','Age','CIBIL_Score','Annual_Household_Income','Debt_to_Income_Ratio','Existing_EMIs','Asset_Value','Monthly_Expense','Loan_to_Annual_Income']]

In [ ]:
matrix = np.array(data)
matrix

array([[2.000000e+00, 5.697600e+04, 1.174700e+01, ..., 7.448610e+05,
        3.039100e+04, 1.174700e+01],
       [0.000000e+00, 1.856000e+03, 4.038100e+01, ..., 0.000000e+00,
        1.856000e+03, 4.038100e+01],
       [0.000000e+00, 6.455300e+04, 3.082000e+00, ..., 2.913766e+06,
        2.455700e+04, 3.082000e+00],
       ...,
       [1.000000e+00, 2.439200e+04, 7.030000e-01, ..., 1.631635e+06,
        2.297700e+04, 7.030000e-01],
       [2.000000e+00, 6.480300e+04, 3.770000e-01, ..., 5.000832e+06,
        7.237600e+04, 3.770000e-01],
       [0.000000e+00, 2.293800e+04, 2.220000e-01, ..., 0.000000e+00,
        1.610500e+04, 2.220000e-01]])

Vector addition

In [ ]:
applicant_income = np.array(df['Applicant_Income'])
coapplicant_income = np.array(df['Coapplicant_Income'])
total_income = applicant_income+coapplicant_income
total_income

array([ 56976,   1856,  64553,  88450,   9539,  39184,  81223,      0,
        17675,  71409,  46972,  38126,  63115,  35034,  53684, 113545,
        29319,  10609,  66474,  95054,  48611,  15509, 117255,  97735,
        45050,  34900,   9381,   3000,  54597,  43481, 143023,  42416,
        92535,  39270,  55899,  33527,  28605,  33983,  23543, 129184,
         3000,  60010,  42393,  48860,  66608,  27205,  52863,  53000,
        91498,  47655,  92893,   1519,  80579,  94207,  55058,  23796,
        33925,  31372, 212945,  39035, 135891,  33478,  46668,  45832,
       136339,  29274,  89323,  66933,  36203,  52935,  33160,   9768,
        85714, 119391,  21455,  36438,  40206,  38127,  12104,      0,
        71887, 112111,   5000,   3000,  28345,   7914,  89966, 101852,
        13318,  80548,  62827,   3884,  21109,  45652,  60198,  13049,
        99076,  99781,  83511,   4812,  82923, 157182,  32371,  13956,
        86493, 108790, 101761,  98367,   7781, 144852,  79239,  92625,
      

vector subtraction

In [ ]:
savings = total_income - np.array(df['Monthly_Expense'])
savings

array([ 26585,      0,  39996,  51700,   5619,  21411,  44078,      0,
         6020,  45192,  35961,  11610,  37146,  20899,  20675,  66848,
        19635,   8609,  41242,  45608,  23656,  12432,  59418,  47545,
        29897,  28549,   7287,      0,  38303,  17167,  87206,  33739,
        48197,  17477,  19230,  16207,  16715,  19916,   6978,  75256,
            0,  30413,  22098,  24590,  32924,  13586,  31722,  22566,
        45901,  28549,  50633,      0,  51629,  53078,  31002,  11539,
        24163,  20933, 119874,  14904,  68647,  19997,  31859,  25823,
        76530,  10424,  46010,  38252,  19929,  28410,  13807,   3905,
        38294,  60474,  10887,  21560,  26064,  27539,      0,      0,
        43251,  68376,      0,   1000,  21045,   4321,  44171,  58858,
        11318,  41852,  24008,      0,  11657,  22359,  34710,   8093,
        60894,  58191,  45008,   2812,  46377,  90470,  19387,   2141,
        52562,  76769,  60283,  53279,   4096,  84704,  33755,  42385,
      

Scalar Multiplication

In [ ]:
increased_savings = 1.1 * savings
increased_savings

array([ 29243.5,      0. ,  43995.6,  56870. ,   6180.9,  23552.1,
        48485.8,      0. ,   6622. ,  49711.2,  39557.1,  12771. ,
        40860.6,  22988.9,  22742.5,  73532.8,  21598.5,   9469.9,
        45366.2,  50168.8,  26021.6,  13675.2,  65359.8,  52299.5,
        32886.7,  31403.9,   8015.7,      0. ,  42133.3,  18883.7,
        95926.6,  37112.9,  53016.7,  19224.7,  21153. ,  17827.7,
        18386.5,  21907.6,   7675.8,  82781.6,      0. ,  33454.3,
        24307.8,  27049. ,  36216.4,  14944.6,  34894.2,  24822.6,
        50491.1,  31403.9,  55696.3,      0. ,  56791.9,  58385.8,
        34102.2,  12692.9,  26579.3,  23026.3, 131861.4,  16394.4,
        75511.7,  21996.7,  35044.9,  28405.3,  84183. ,  11466.4,
        50611. ,  42077.2,  21921.9,  31251. ,  15187.7,   4295.5,
        42123.4,  66521.4,  11975.7,  23716. ,  28670.4,  30292.9,
            0. ,      0. ,  47576.1,  75213.6,      0. ,   1100. ,
        23149.5,   4753.1,  48588.1,  64743.8,  12449.8,  4603

Vector dot product

In [ ]:
cibil_score = np.array(df['CIBIL_Score'])
dot_product = np.dot(total_income,cibil_score)
dot_product

np.int64(34171576709)

Matrix Creation

In [ ]:
financial_matrix = np.array(df[
    ['Applicant_Income','Coapplicant_Income','Loan_Amount','CIBIL_Score','Monthly_Expense']
]
)
financial_matrix

array([[  56976,       0, 8031545,     699,   30391],
       [   1856,       0,  899361,     707,    1856],
       [  64553,       0, 2387748,     641,   24557],
       ...,
       [  24392,   11337,  301249,     725,   22977],
       [  64803,   94136,  719891,     679,   72376],
       [  22938,       0,   61019,     690,   16105]])

Matrix Addition

In [ ]:
A=financial_matrix[:2]
B=financial_matrix[2:4]
matrix_addition= A+B
matrix_addition

array([[  121529,        0, 10419293,     1340,    54948],
       [   90306,        0,  1558217,     1384,    38606]])

Matrix-Vector Multiplication

In [ ]:
A=np.array(df[['Applicant_Income','Coapplicant_Income','Monthly_Expense']].head(3))
vector=np.array(df['Debt_to_Income_Ratio'].head(3))
matrix_vector_multiplication=np.dot(A,vector)
matrix_vector_multiplication

array([5583.648,  181.888, 6326.194])

Matrix-Matrix Multiplication

In [ ]:
A=np.array(df[["Applicant_Income","Coapplicant_Income"]])
B=np.array(df[["Loan_Amount","CIBIL_Score"]])
matrix_matrix_multiplication=np.dot(A,B.T)
matrix_matrix_multiplication

array([[457605307920,  51241992336, 136044330048, ...,  17163963024,
         41016509616,   3476618544],
       [ 14906547520,   1669214016,   4431660288, ...,    559118144,
          1336117696,    113251264],
       [518460324385,  58056450633, 154136296644, ...,  19446526697,
         46471123723,   3938959507],
       ...,
       [195913370203,  21945228771,  58249216233, ...,   7356284933,
         17567279095,   1496197978],
       [520534011699,  58347845035, 154793574820, ...,  19590087547,
         46715014817,   4019168097],
       [184227579210,  20629542618,  54770163624, ...,   6910049562,
         16512859758,   1399653822]])

Find Rank in Numpy->

In [ ]:
A=np.array(df[["Applicant_Income","Coapplicant_Income"]])
rank = np.linalg.matrix_rank(A)
rank

np.int64(2)